/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author david
 */
public class NewJFrame extends javax.swing.JFrame {
    public static Management m = new Management();
   
    /**
     * Creates new form NewJFrame
     */
    CardLayout cardLayout;
    public NewJFrame() {
        initComponents();
        cardLayout = (CardLayout)(rightCardPanel.getLayout());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        mainMenu = new javax.swing.JPanel();
        appointmentButton = new javax.swing.JButton();
        clientsButton = new javax.swing.JButton();
        employeesButton = new javax.swing.JButton();
        servicesButton = new javax.swing.JButton();
        salesButton = new javax.swing.JButton();
        mainTitleLabel = new javax.swing.JLabel();
        rightCardPanel = new javax.swing.JPanel();
        appointmentPanel = new javax.swing.JPanel();
        appointmentTabs = new javax.swing.JTabbedPane();
        CalendarPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        appointCreatePane = new javax.swing.JPanel();
        appointModifyPane = new javax.swing.JPanel();
        appointDeletePane = new javax.swing.JPanel();
        appointmentLabel = new javax.swing.JLabel();
        clientsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jTabbedPane22 = new javax.swing.JTabbedPane();
        jTabbedPane23 = new javax.swing.JTabbedPane();
        jTabbedPane24 = new javax.swing.JTabbedPane();
        jTabbedPane25 = new javax.swing.JTabbedPane();
        jTabbedPane26 = new javax.swing.JTabbedPane();
        jTabbedPane27 = new javax.swing.JTabbedPane();
        jTabbedPane28 = new javax.swing.JTabbedPane();
        jTabbedPane29 = new javax.swing.JTabbedPane();
        employeesPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane16 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane12 = new javax.swing.JTabbedPane();
        jTabbedPane18 = new javax.swing.JTabbedPane();
        jTabbedPane19 = new javax.swing.JTabbedPane();
        jTabbedPane20 = new javax.swing.JTabbedPane();
        jTabbedPane21 = new javax.swing.JTabbedPane();
        servicesPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        serviceTabs = new javax.swing.JTabbedPane();
        serviceMainTab = new javax.swing.JPanel();
        serviceChoice = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        serviceListOptions = new javax.swing.JList<>();
        selectOption = new javax.swing.JLabel();
        invalidOption = new javax.swing.JLabel();
        serviceEnterNumber = new java.awt.TextField();
        serviceMessage = new javax.swing.JLabel();
        serviceCreateTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        serviceName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        servicePrice = new javax.swing.JTextField();
        serviceCreateButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviceDescription = new javax.swing.JTextArea();
        serviceModifyTab = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        serviceModifiedPrice = new javax.swing.JTextField();
        serviceModifyButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        serviceModifySelectionDescription = new javax.swing.JTextArea();
        serviceDropDown = new javax.swing.JComboBox<>();
        serviceSelectModify = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        serviceModifySelectionLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        serviceModifySelectionName = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        serviceModifySelectionPrice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        serviceModifiedName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        serviceModifiedDescription = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        lastServiceModified = new javax.swing.JLabel();
        salesPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carwash Management System");

        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setDividerSize(0);

        mainMenu.setBackground(new java.awt.Color(0, 204, 255));
        mainMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 102, 255)));
        mainMenu.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N

        appointmentButton.setBackground(new java.awt.Color(0, 153, 255));
        appointmentButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        appointmentButton.setForeground(new java.awt.Color(0, 0, 51));
        appointmentButton.setText("Appointments");
        appointmentButton.setBorderPainted(false);
        appointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentButtonActionPerformed(evt);
            }
        });

        clientsButton.setBackground(new java.awt.Color(0, 153, 255));
        clientsButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        clientsButton.setForeground(new java.awt.Color(0, 0, 51));
        clientsButton.setText("Clients");
        clientsButton.setBorderPainted(false);
        clientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsButtonActionPerformed(evt);
            }
        });

        employeesButton.setBackground(new java.awt.Color(0, 153, 255));
        employeesButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        employeesButton.setForeground(new java.awt.Color(0, 0, 51));
        employeesButton.setText("Employees");
        employeesButton.setBorderPainted(false);
        employeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesButtonActionPerformed(evt);
            }
        });

        servicesButton.setBackground(new java.awt.Color(0, 153, 255));
        servicesButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        servicesButton.setForeground(new java.awt.Color(0, 0, 51));
        servicesButton.setText("Services");
        servicesButton.setBorderPainted(false);
        servicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesButtonActionPerformed(evt);
            }
        });

        salesButton.setBackground(new java.awt.Color(0, 153, 255));
        salesButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        salesButton.setForeground(new java.awt.Color(0, 0, 51));
        salesButton.setText("Sales");
        salesButton.setBorderPainted(false);
        salesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesButtonActionPerformed(evt);
            }
        });

        mainTitleLabel.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        mainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleLabel.setText("Carwash Management");

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(mainTitleLabel))
                    .addGroup(mainMenuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(servicesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employeesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appointmentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(mainTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appointmentButton)
                .addGap(18, 18, 18)
                .addComponent(clientsButton)
                .addGap(18, 18, 18)
                .addComponent(employeesButton)
                .addGap(18, 18, 18)
                .addComponent(servicesButton)
                .addGap(18, 18, 18)
                .addComponent(salesButton)
                .addGap(124, 124, 124))
        );

        jSplitPane2.setLeftComponent(mainMenu);

        rightCardPanel.setLayout(new java.awt.CardLayout());

        appointmentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        appointmentTabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Testing Commit");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("Test");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalendarPaneLayout = new javax.swing.GroupLayout(CalendarPane);
        CalendarPane.setLayout(CalendarPaneLayout);
        CalendarPaneLayout.setHorizontalGroup(
            CalendarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalendarPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(CalendarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalendarPaneLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CalendarPaneLayout.setVerticalGroup(
            CalendarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalendarPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalendarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton1))
                .addContainerGap(418, Short.MAX_VALUE))
        );

        appointmentTabs.addTab("Calendar", CalendarPane);

        javax.swing.GroupLayout appointCreatePaneLayout = new javax.swing.GroupLayout(appointCreatePane);
        appointCreatePane.setLayout(appointCreatePaneLayout);
        appointCreatePaneLayout.setHorizontalGroup(
            appointCreatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        appointCreatePaneLayout.setVerticalGroup(
            appointCreatePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        appointmentTabs.addTab("Create", appointCreatePane);

        javax.swing.GroupLayout appointModifyPaneLayout = new javax.swing.GroupLayout(appointModifyPane);
        appointModifyPane.setLayout(appointModifyPaneLayout);
        appointModifyPaneLayout.setHorizontalGroup(
            appointModifyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        appointModifyPaneLayout.setVerticalGroup(
            appointModifyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        appointmentTabs.addTab("Modify", appointModifyPane);

        javax.swing.GroupLayout appointDeletePaneLayout = new javax.swing.GroupLayout(appointDeletePane);
        appointDeletePane.setLayout(appointDeletePaneLayout);
        appointDeletePaneLayout.setHorizontalGroup(
            appointDeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        appointDeletePaneLayout.setVerticalGroup(
            appointDeletePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        appointmentTabs.addTab("Delete", appointDeletePane);

        appointmentLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        appointmentLabel.setText("Appointments");

        javax.swing.GroupLayout appointmentPanelLayout = new javax.swing.GroupLayout(appointmentPanel);
        appointmentPanel.setLayout(appointmentPanelLayout);
        appointmentPanelLayout.setHorizontalGroup(
            appointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appointmentTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(appointmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appointmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        appointmentPanelLayout.setVerticalGroup(
            appointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentPanelLayout.createSequentialGroup()
                .addComponent(appointmentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentTabs))
        );

        rightCardPanel.add(appointmentPanel, "appointmentPanel");

        clientsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 102, 255)));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Clients");

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("1: Create Client", jPanel5);
        jTabbedPane2.addTab(" 2: Delete Client", jTabbedPane17);
        jTabbedPane2.addTab(" 3: Modify Client", jTabbedPane22);
        jTabbedPane2.addTab(" 4: Change Client's Membership tier", jTabbedPane23);
        jTabbedPane2.addTab(" 5: Add Client's Cars", jTabbedPane24);
        jTabbedPane2.addTab(" 6: Remove Client's Cars", jTabbedPane25);
        jTabbedPane2.addTab("7: Modify Client's Cars", jTabbedPane26);
        jTabbedPane2.addTab(" 8: View Client Info", jTabbedPane27);
        jTabbedPane2.addTab("9: View List of Clients", jTabbedPane28);
        jTabbedPane2.addTab("10: Return to the Main Menu", jTabbedPane29);

        javax.swing.GroupLayout clientsPanelLayout = new javax.swing.GroupLayout(clientsPanel);
        clientsPanel.setLayout(clientsPanelLayout);
        clientsPanelLayout.setHorizontalGroup(
            clientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane2)
        );
        clientsPanelLayout.setVerticalGroup(
            clientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2))
        );

        rightCardPanel.add(clientsPanel, "clientsPanel");

        employeesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Employees");

        jTabbedPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jTabbedPane3.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTabbedPane3HierarchyChanged(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1: Create Employee", "2: Delete Employee", "3: Modify Employee", "4: View Employee Info", "5: View List of Employees", "6: Return to the Main Menu", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        jTabbedPane16.addTab("What would you like to do? ", jScrollPane5);

        jTabbedPane3.addTab("Main - Page", jTabbedPane16);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab(" 1: Create Employee", jPanel6);
        jTabbedPane3.addTab(" 2: Delete Employee", jTabbedPane12);
        jTabbedPane3.addTab(" 3: Modify Employee", jTabbedPane18);
        jTabbedPane3.addTab(" 4: View Employee Info", jTabbedPane19);
        jTabbedPane3.addTab(" 5: View List of Employees", jTabbedPane20);
        jTabbedPane3.addTab(" 6: Return to the Main Menu", jTabbedPane21);

        javax.swing.GroupLayout employeesPanelLayout = new javax.swing.GroupLayout(employeesPanel);
        employeesPanel.setLayout(employeesPanelLayout);
        employeesPanelLayout.setHorizontalGroup(
            employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane3))
                .addContainerGap())
        );
        employeesPanelLayout.setVerticalGroup(
            employeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeesPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3))
        );

        rightCardPanel.add(employeesPanel, "employeesPanel");

        servicesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Services");

        serviceTabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        serviceChoice.setText("What would you like to do?");

        serviceListOptions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1: Create Service", "2: Delete Service", "3: Modify Service", "4: Create Member Tier", "5: Delete Member Tier", "6: Modify Member Tier", "7: View Service Info", "8: View List of Services", "9: View Member Tier Info", "10: List of Member Tiers", "11: Return to the Main Menu" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(serviceListOptions);

        selectOption.setText("To select an option, enter the corresponding number:  1-11");

        invalidOption.setText("You entered an invalid option. Please try again: ");

        serviceEnterNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceEnterNumberActionPerformed(evt);
            }
        });

        serviceMessage.setText("If you enter a number outside of : 1-11  It will prompt an error message.");

        javax.swing.GroupLayout serviceMainTabLayout = new javax.swing.GroupLayout(serviceMainTab);
        serviceMainTab.setLayout(serviceMainTabLayout);
        serviceMainTabLayout.setHorizontalGroup(
            serviceMainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceMainTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(serviceMainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serviceMainTabLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(serviceEnterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalidOption, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceMessage)
                    .addComponent(selectOption)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceChoice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        serviceMainTabLayout.setVerticalGroup(
            serviceMainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceMainTabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(serviceChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectOption, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceEnterNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(serviceMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidOption, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        serviceTabs.addTab("Main", serviceMainTab);

        jLabel6.setText("Enter the name of the new service: ");

        serviceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceNameActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter the description of the new service: ");

        jLabel8.setText("Enter the price of the new service: ");

        servicePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicePriceActionPerformed(evt);
            }
        });

        serviceCreateButton.setText("Create New Service");
        serviceCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceCreateButtonActionPerformed(evt);
            }
        });

        serviceDescription.setColumns(20);
        serviceDescription.setRows(5);
        jScrollPane2.setViewportView(serviceDescription);

        javax.swing.GroupLayout serviceCreateTabLayout = new javax.swing.GroupLayout(serviceCreateTab);
        serviceCreateTab.setLayout(serviceCreateTabLayout);
        serviceCreateTabLayout.setHorizontalGroup(
            serviceCreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceCreateTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(serviceCreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serviceCreateTabLayout.createSequentialGroup()
                        .addGroup(serviceCreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(serviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(serviceCreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, serviceCreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(serviceCreateButton)
                            .addGroup(serviceCreateTabLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(servicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        serviceCreateTabLayout.setVerticalGroup(
            serviceCreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceCreateTabLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(serviceCreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(serviceCreateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(servicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(serviceCreateButton)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        serviceTabs.addTab("Create", serviceCreateTab);

        jLabel9.setText("Choose the service you want to modify");

        jLabel10.setText("Name:");

        jLabel11.setText("Changed Price:");

        serviceModifiedPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceModifiedPriceActionPerformed(evt);
            }
        });

        serviceModifyButton.setText("Modify Service");
        serviceModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceModifyButtonActionPerformed(evt);
            }
        });

        serviceModifySelectionDescription.setEditable(false);
        serviceModifySelectionDescription.setColumns(20);
        serviceModifySelectionDescription.setRows(5);
        serviceModifySelectionDescription.setText("None");
        jScrollPane6.setViewportView(serviceModifySelectionDescription);

        serviceDropDown.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                serviceDropDownFocusGained(evt);
            }
        });
        serviceDropDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceDropDownMouseClicked(evt);
            }
        });
        serviceDropDown.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                serviceDropDownInputMethodTextChanged(evt);
            }
        });
        serviceDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceDropDownActionPerformed(evt);
            }
        });
        serviceDropDown.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                serviceDropDownPropertyChange(evt);
            }
        });

        serviceSelectModify.setText("Select");
        serviceSelectModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceSelectModifyActionPerformed(evt);
            }
        });

        jLabel12.setText("You have chosen");

        serviceModifySelectionLabel.setText("(selection)");
        serviceModifySelectionLabel.setName(""); // NOI18N

        jLabel13.setText("Description:");

        serviceModifySelectionName.setText("None");

        jLabel15.setText("Price:");

        serviceModifySelectionPrice.setText("None");

        jLabel14.setText("Changed Name:");

        serviceModifiedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceModifiedNameActionPerformed(evt);
            }
        });

        jLabel16.setText("Changed Description:");

        serviceModifiedDescription.setColumns(20);
        serviceModifiedDescription.setRows(5);
        jScrollPane7.setViewportView(serviceModifiedDescription);

        jLabel17.setText("Last Service Modified:");

        lastServiceModified.setText("None");

        javax.swing.GroupLayout serviceModifyTabLayout = new javax.swing.GroupLayout(serviceModifyTab);
        serviceModifyTab.setLayout(serviceModifyTabLayout);
        serviceModifyTabLayout.setHorizontalGroup(
            serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceModifyTabLayout.createSequentialGroup()
                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serviceModifyTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(serviceModifyTabLayout.createSequentialGroup()
                        .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(serviceModifyTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(serviceModifyTabLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceModifySelectionPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(serviceModifyTabLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(serviceModifyTabLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceModifySelectionName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(serviceModifyTabLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceModifySelectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(serviceModifyTabLayout.createSequentialGroup()
                                        .addComponent(serviceDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(serviceSelectModify, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(serviceModifyTabLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(serviceModifiedName))
                                    .addComponent(jLabel16)
                                    .addComponent(jScrollPane7)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serviceModifyTabLayout.createSequentialGroup()
                                        .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, serviceModifyTabLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lastServiceModified, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(serviceModifyTabLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(serviceModifiedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(150, 150, 150)))))
                        .addGap(0, 344, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(serviceModifyTabLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(serviceModifyButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        serviceModifyTabLayout.setVerticalGroup(
            serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceModifyTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceSelectModify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(serviceModifySelectionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(serviceModifySelectionName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceModifySelectionPrice)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(serviceModifiedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(serviceModifiedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(serviceModifyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(serviceModifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lastServiceModified))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        serviceTabs.addTab("Modify", serviceModifyTab);

        javax.swing.GroupLayout servicesPanelLayout = new javax.swing.GroupLayout(servicesPanel);
        servicesPanel.setLayout(servicesPanelLayout);
        servicesPanelLayout.setHorizontalGroup(
            servicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(serviceTabs)
        );
        servicesPanelLayout.setVerticalGroup(
            servicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceTabs))
        );

        rightCardPanel.add(servicesPanel, "servicesPanel");

        salesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Sales");

        jTabbedPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("tab1", jPanel8);

        javax.swing.GroupLayout salesPanelLayout = new javax.swing.GroupLayout(salesPanel);
        salesPanel.setLayout(salesPanelLayout);
        salesPanelLayout.setHorizontalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane5)
        );
        salesPanelLayout.setVerticalGroup(
            salesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane5))
        );

        rightCardPanel.add(salesPanel, "salesPanel");

        jSplitPane2.setRightComponent(rightCardPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        setSize(new java.awt.Dimension(1012, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(rightCardPanel, "clientsPanel");
    }//GEN-LAST:event_clientsButtonActionPerformed

    private void appointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(rightCardPanel,"appointmentPanel");
    }//GEN-LAST:event_appointmentButtonActionPerformed

    private void employeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(rightCardPanel,"employeesPanel");
       
    }//GEN-LAST:event_employeesButtonActionPerformed

    private void servicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(rightCardPanel,"servicesPanel");
    }//GEN-LAST:event_servicesButtonActionPerformed

    private void salesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(rightCardPanel, "salesPanel");
    }//GEN-LAST:event_salesButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void serviceEnterNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceEnterNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceEnterNumberActionPerformed

    private void jTabbedPane3HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTabbedPane3HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane3HierarchyChanged

    private void serviceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceNameActionPerformed

    private void servicePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicePriceActionPerformed

    private void serviceCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCreateButtonActionPerformed
        // TODO add your handling code here:
            String name = serviceName.getText();
            Double price = Double.parseDouble(servicePrice.getText());
            String description = serviceDescription.getText();
           
        m.createServiceGUI(name,description,price);
        m.printListService();
        serviceName.setText("");
        servicePrice.setText("");
        serviceDescription.setText("");
    }//GEN-LAST:event_serviceCreateButtonActionPerformed

    private void serviceModifiedPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceModifiedPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceModifiedPriceActionPerformed

    private void serviceModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceModifyButtonActionPerformed
        // TODO add your handling code here:
        String oldName = serviceModifySelectionName.getText();
        String newName = serviceModifiedName.getText();
        String newDesc = serviceModifiedDescription.getText();
        double newPrice = Integer.valueOf(serviceModifiedPrice.getText());
        
        m.removeServiceGUI(oldName);
        m.createServiceGUI(newName, newDesc,newPrice);
        
        lastServiceModified.setText(newName);
        serviceModifySelectionName.setText("");
        serviceModifiedName.setText("");
        serviceModifiedDescription.setText("");
        serviceModifiedPrice.setText("");
        serviceModifySelectionDescription.setText("");
        serviceModifySelectionPrice.setText("");
        
        String[] keyArray = m.services.keySet().toArray(new String[m.services.size()]);
        serviceDropDown.setModel(new DefaultComboBoxModel<>(keyArray));
        
        
    }//GEN-LAST:event_serviceModifyButtonActionPerformed

    private void serviceDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceDropDownActionPerformed
         
    }//GEN-LAST:event_serviceDropDownActionPerformed

    private void serviceDropDownInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_serviceDropDownInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceDropDownInputMethodTextChanged

    private void serviceDropDownPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_serviceDropDownPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_serviceDropDownPropertyChange

    private void serviceDropDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceDropDownMouseClicked
       
    }//GEN-LAST:event_serviceDropDownMouseClicked

    private void serviceDropDownFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_serviceDropDownFocusGained
        // TODO add your handling code here:
        String[] keyArray = m.services.keySet().toArray(new String[m.services.size()]);
        serviceDropDown.setModel(new DefaultComboBoxModel<>(keyArray));
    }//GEN-LAST:event_serviceDropDownFocusGained

    private void serviceSelectModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceSelectModifyActionPerformed
        // TODO add your handling code here:
        serviceModifySelectionLabel.setText(serviceDropDown.getSelectedItem().toString()); 
        serviceModifySelectionName.setText(m.services.get(serviceDropDown.getSelectedItem().toString()).getServiceName());
        serviceModifySelectionDescription.setText(m.services.get(serviceDropDown.getSelectedItem().toString()).getDescription());
        
        serviceModifySelectionPrice.setText("$" + String.valueOf(m.services.get(serviceDropDown.getSelectedItem().toString()).getPrice()));


    }//GEN-LAST:event_serviceSelectModifyActionPerformed

    private void serviceModifiedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceModifiedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceModifiedNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalendarPane;
    private javax.swing.JPanel appointCreatePane;
    private javax.swing.JPanel appointDeletePane;
    private javax.swing.JPanel appointModifyPane;
    private javax.swing.JButton appointmentButton;
    private javax.swing.JLabel appointmentLabel;
    private javax.swing.JPanel appointmentPanel;
    private javax.swing.JTabbedPane appointmentTabs;
    private javax.swing.JButton clientsButton;
    private javax.swing.JPanel clientsPanel;
    private javax.swing.JButton employeesButton;
    private javax.swing.JPanel employeesPanel;
    private javax.swing.JLabel invalidOption;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane12;
    private javax.swing.JTabbedPane jTabbedPane16;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTabbedPane jTabbedPane18;
    private javax.swing.JTabbedPane jTabbedPane19;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane20;
    private javax.swing.JTabbedPane jTabbedPane21;
    private javax.swing.JTabbedPane jTabbedPane22;
    private javax.swing.JTabbedPane jTabbedPane23;
    private javax.swing.JTabbedPane jTabbedPane24;
    private javax.swing.JTabbedPane jTabbedPane25;
    private javax.swing.JTabbedPane jTabbedPane26;
    private javax.swing.JTabbedPane jTabbedPane27;
    private javax.swing.JTabbedPane jTabbedPane28;
    private javax.swing.JTabbedPane jTabbedPane29;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lastServiceModified;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JPanel rightCardPanel;
    private javax.swing.JButton salesButton;
    private javax.swing.JPanel salesPanel;
    private javax.swing.JLabel selectOption;
    private javax.swing.JLabel serviceChoice;
    private javax.swing.JButton serviceCreateButton;
    private javax.swing.JPanel serviceCreateTab;
    private javax.swing.JTextArea serviceDescription;
    private javax.swing.JComboBox<String> serviceDropDown;
    private java.awt.TextField serviceEnterNumber;
    private javax.swing.JList<String> serviceListOptions;
    private javax.swing.JPanel serviceMainTab;
    private javax.swing.JLabel serviceMessage;
    private javax.swing.JTextArea serviceModifiedDescription;
    private javax.swing.JTextField serviceModifiedName;
    private javax.swing.JTextField serviceModifiedPrice;
    private javax.swing.JButton serviceModifyButton;
    private javax.swing.JTextArea serviceModifySelectionDescription;
    private javax.swing.JLabel serviceModifySelectionLabel;
    private javax.swing.JLabel serviceModifySelectionName;
    private javax.swing.JLabel serviceModifySelectionPrice;
    private javax.swing.JPanel serviceModifyTab;
    private javax.swing.JTextField serviceName;
    private javax.swing.JTextField servicePrice;
    private javax.swing.JButton serviceSelectModify;
    private javax.swing.JTabbedPane serviceTabs;
    private javax.swing.JButton servicesButton;
    private javax.swing.JPanel servicesPanel;
    // End of variables declaration//GEN-END:variables
}
